### ISSUE TITLE
Dangling line on the Top layer

### ISSUE THREAD

**Issue by nsinav** [roybaer/renovation_ssi_2001#4]
Hello,
I have a question. Recently I found that there is a dangling line on the Top layer, as shown in the figure below. Does this affect the function? I send you pics. Thank you.
![dangling line](https://github.com/roybaer/renovation_ssi_2001/assets/34785779/ea06f952-be27-49b8-8f51-ab2878bcd580)

**Comment by roybaer** [comment]
It doesn't, because it is there for looks, only.
The historical layout of the Innovation SSI-2001 ran a trace from that VIA to pin 1 of the NE558 on the top layer below the chip, but this modified layout hides the footprints for optional modern replacements under there, so that pin 1 is now connected via a new trace on the bottom layer.

**Comment by nsinav** [comment]
Thank you sir, you are very kind
